# Generated by Django 3.2.7 on 2021-10-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choce_text',
            new_name='choice_text',
        ),
    ]
